-- =====================================================================
-- PROYECTO INTEGRADOR: BioUTN - BASE DE DATOS MAESTRA (EF CORE + v3)
-- =====================================================================
-- Motor      : PostgreSQL 15+
-- Enfoque    : Trazabilidad Biotecnológica y Gestión de Laboratorio
-- Nomenclatura: PascalCase, Comillas Dobles, Identity PK (EF Core Standard)
-- Tablas     : 24
-- =====================================================================

BEGIN;

-- ─────────────────────────────────────────────────────────────────────
-- 1. ADMINISTRACIÓN Y SEGURIDAD (4 Tablas)
-- ─────────────────────────────────────────────────────────────────────

CREATE TABLE IF NOT EXISTS public."Roles"
(
    "Id" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "NombreRol" character varying(50) NOT NULL
);

CREATE TABLE IF NOT EXISTS public."TiposIdentificacion"
(
    "Id" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "NombreTipo" character varying(50) NOT NULL
);

CREATE TABLE IF NOT EXISTS public."Generos"
(
    "Id" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "NombreGenero" character varying(50) NOT NULL
);

CREATE TABLE IF NOT EXISTS public."Usuarios"
(
    "Id" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "IdRol" integer NOT NULL REFERENCES public."Roles"("Id") ON DELETE RESTRICT,
    "IdTipoIdentificacion" integer NOT NULL REFERENCES public."TiposIdentificacion"("Id") ON DELETE RESTRICT,
    "NumeroIdentificacion" character varying(20) NOT NULL UNIQUE,
    "IdGenero" integer NOT NULL REFERENCES public."Generos"("Id") ON DELETE RESTRICT,
    "Nombres" character varying(100) NOT NULL,
    "Apellidos" character varying(100) NOT NULL,
    "Email" character varying(100) NOT NULL UNIQUE,
    "Telefono" character varying(15),
    "ContrasenaHash" text NOT NULL,
    "IntentosFallidos" integer NOT NULL DEFAULT 0,
    "CuentaBloqueada" boolean NOT NULL DEFAULT false,
    "Activo" boolean NOT NULL DEFAULT true
);

-- ─────────────────────────────────────────────────────────────────────
-- 2. BIOLOGÍA: TAXONOMÍA Y ESPECIES (3 Tablas)
-- ─────────────────────────────────────────────────────────────────────

CREATE TABLE IF NOT EXISTS public."TiposPlanta"
(
    "Id" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "Nombre" character varying(50) NOT NULL
);

CREATE TABLE IF NOT EXISTS public."Taxonomia"
(
    "Id" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "Dominio" character varying(50) NOT NULL DEFAULT 'Eukaryota',
    "Reino" character varying(50) NOT NULL DEFAULT 'Plantae',
    "SubReino" character varying(50),       -- Opcional
    "FiloDivision" character varying(50) NOT NULL,
    "Clase" character varying(50) NOT NULL,
    "Orden" character varying(50) NOT NULL,
    "Familia" character varying(50) NOT NULL,
    "SubFamilia" character varying(50),     -- Opcional
    "Tribu" character varying(50),          -- Opcional
    "SubTribu" character varying(50),       -- Opcional
    "Genero" character varying(50) NOT NULL,
    "Especie" character varying(100) NOT NULL
);

CREATE TABLE IF NOT EXISTS public."Especies"
(
    "Id" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "IdTaxonomia" integer NOT NULL REFERENCES public."Taxonomia"("Id") ON DELETE RESTRICT,
    "IdTipoPlanta" integer NOT NULL REFERENCES public."TiposPlanta"("Id") ON DELETE RESTRICT,
    "CodigoEstricto" character varying(10) NOT NULL UNIQUE,
    "NombreCientifico" character varying(100) NOT NULL,
    "NombreComun" character varying(100) NOT NULL,
    "PeligroExtincion" boolean NOT NULL DEFAULT false,
    "DiasResiembra" smallint NOT NULL DEFAULT 90,
    "MaxResiembras" smallint NOT NULL DEFAULT 10,
    "Activo" boolean NOT NULL DEFAULT true
);

-- ─────────────────────────────────────────────────────────────────────
-- 3. PROYECTOS Y GESTIÓN OPERATIVA (2 Tablas)
-- ─────────────────────────────────────────────────────────────────────

CREATE TABLE IF NOT EXISTS public."Proyectos"
(
    "Id" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "NombreProyecto" character varying(150) NOT NULL,
    "Descripcion" text NOT NULL,
    "TipoProyecto" character varying(50) NOT NULL,
    "Estado" character varying(20) NOT NULL,
    "FechaInicio" timestamp with time zone NOT NULL,
    "FechaFin" timestamp with time zone,
    "IdUsuarioResponsable" integer NOT NULL REFERENCES public."Usuarios"("Id") ON DELETE RESTRICT
);

CREATE TABLE IF NOT EXISTS public."TareasOperativas"
(
    "Id" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "IdUsuario" integer NOT NULL REFERENCES public."Usuarios"("Id") ON DELETE RESTRICT,
    "TipoTarea" character varying(100) NOT NULL,
    "Estado" character varying(20) NOT NULL,
    "FechaAsignacion" timestamp with time zone NOT NULL,
    "FechaCompletada" timestamp with time zone
);

-- ─────────────────────────────────────────────────────────────────────
-- 4. TRAZABILIDAD: PLANTAS, LOTES Y FRASCOS (7 Tablas)
-- ─────────────────────────────────────────────────────────────────────

CREATE TABLE IF NOT EXISTS public."PlantasMadre"
(
    "Id" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "IdEspecie" integer NOT NULL REFERENCES public."Especies"("Id") ON DELETE RESTRICT,
    "IdProyecto" integer NOT NULL REFERENCES public."Proyectos"("Id") ON DELETE RESTRICT,
    "IdUsuario" integer NOT NULL REFERENCES public."Usuarios"("Id") ON DELETE RESTRICT,
    "CodigoAsignado" character varying(20) NOT NULL UNIQUE,
    "FechaIntroduccion" timestamp with time zone NOT NULL,
    "EstadoFitosanitario" character varying(50) NOT NULL,
    "UrlFotografia" text,
    "UrlQr" text,
    "Activo" boolean NOT NULL DEFAULT true
);

CREATE TABLE IF NOT EXISTS public."PermisosAmbientales"
(
    "Id" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "IdPlantaMadre" integer NOT NULL REFERENCES public."PlantasMadre"("Id") ON DELETE RESTRICT,
    "NumeroResolucion" character varying(100) NOT NULL,
    "UrlArchivoPdf" text NOT NULL,
    "FechaEmision" timestamp with time zone NOT NULL
);

CREATE TABLE IF NOT EXISTS public."MediosCultivo"
(
    "Id" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "Siglas" character varying(15) NOT NULL,
    "Descripcion" character varying(150) NOT NULL,
    "Componentes" text NOT NULL,
    "IdUsuarioPropietario" integer REFERENCES public."Usuarios"("Id") ON DELETE SET NULL
);

CREATE TABLE IF NOT EXISTS public."FasesCultivo"
(
    "Id" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "NombreFase" character varying(50) NOT NULL
);

CREATE TABLE IF NOT EXISTS public."UbicacionesFisicas"
(
    "Id" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "CodigoAnaquel" character varying(20) NOT NULL,
    "NombreCuerpo" character varying(50) NOT NULL,
    "NumeroPiso" integer NOT NULL,
    "EstadoUbicacion" character varying(20) NOT NULL
);

CREATE TABLE IF NOT EXISTS public."LotesCultivo"
(
    "Id" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "IdPlantaMadre" integer NOT NULL REFERENCES public."PlantasMadre"("Id") ON DELETE RESTRICT,
    "IdLotePadre" integer REFERENCES public."LotesCultivo"("Id") ON DELETE RESTRICT,
    "IdMedioCultivo" integer NOT NULL REFERENCES public."MediosCultivo"("Id") ON DELETE RESTRICT,
    "IdProyecto" integer NOT NULL REFERENCES public."Proyectos"("Id") ON DELETE RESTRICT,
    "IdUbicacionFisica" integer NOT NULL REFERENCES public."UbicacionesFisicas"("Id") ON DELETE RESTRICT,
    "IdFaseCultivo" integer NOT NULL REFERENCES public."FasesCultivo"("Id") ON DELETE RESTRICT,
    "IdUsuario" integer NOT NULL REFERENCES public."Usuarios"("Id") ON DELETE RESTRICT,
    "CodigoTrazabilidad" character varying(50) NOT NULL UNIQUE,
    "NumeroRepique" integer NOT NULL DEFAULT 0,
    "FechaSiembra" timestamp with time zone NOT NULL,
    "TotalUnidades" integer NOT NULL,
    "ChecklistSiembra" jsonb, 
    "UrlQr" text,
    "Activo" boolean NOT NULL DEFAULT true
);

CREATE TABLE IF NOT EXISTS public."UnidadesFrasco"
(
    "Id" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "IdLoteCultivo" integer NOT NULL REFERENCES public."LotesCultivo"("Id") ON DELETE RESTRICT,
    "CodigoUnidad" character varying(100) NOT NULL UNIQUE,
    "NumeroResiembra" integer NOT NULL DEFAULT 0,
    "Estado" character varying(30) NOT NULL DEFAULT 'Saludable',
    "UrlQr" text,
    "Activo" boolean NOT NULL DEFAULT true
);

-- ─────────────────────────────────────────────────────────────────────
-- 5. MONITOREO Y EVIDENCIA CIENTÍFICA (3 Tablas)
-- ─────────────────────────────────────────────────────────────────────

CREATE TABLE IF NOT EXISTS public."MonitoreosFitosanitarios"
(
    "Id" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "IdUnidadFrasco" integer NOT NULL REFERENCES public."UnidadesFrasco"("Id") ON DELETE RESTRICT,
    "IdUsuario" integer NOT NULL REFERENCES public."Usuarios"("Id") ON DELETE RESTRICT,
    "FechaEvaluacion" timestamp with time zone NOT NULL,
    "NivelFenolizacion" character varying(20) NOT NULL,
    "NivelContaminacion" character varying(20) NOT NULL,
    "Bacterias" boolean NOT NULL DEFAULT false,
    "Hongos" boolean NOT NULL DEFAULT false,
    "Observaciones" text NOT NULL
);

CREATE TABLE IF NOT EXISTS public."EntradasDiario"
(
    "Id" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "IdProyecto" integer NOT NULL REFERENCES public."Proyectos"("Id") ON DELETE RESTRICT,
    "IdUsuario" integer NOT NULL REFERENCES public."Usuarios"("Id") ON DELETE RESTRICT,
    "IdLoteCultivo" integer REFERENCES public."LotesCultivo"("Id") ON DELETE SET NULL,
    "FechaRegistro" timestamp with time zone NOT NULL,
    "Titulo" character varying(150) NOT NULL,
    "Contenido" text NOT NULL
);

CREATE TABLE IF NOT EXISTS public."Protocolos"
(
    "Id" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "IdEspecie" integer REFERENCES public."Especies"("Id") ON DELETE SET NULL,
    "IdUsuarioAutor" integer NOT NULL REFERENCES public."Usuarios"("Id") ON DELETE RESTRICT,
    "FaseProtocolo" character varying(50) NOT NULL,
    "Titulo" character varying(150) NOT NULL,
    "Descripcion" text NOT NULL,
    "UrlArchivoPdf" text,
    "FechaCreacion" timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "Activo" boolean NOT NULL DEFAULT true
);

-- ─────────────────────────────────────────────────────────────────────
-- 6. EQUIPOS, RESERVAS E INVENTARIO (5 Tablas)
-- ─────────────────────────────────────────────────────────────────────

CREATE TABLE IF NOT EXISTS public."Equipos"
(
    "Id" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "CodigoInventario" character varying(20) NOT NULL UNIQUE,
    "Nombre" character varying(100) NOT NULL,
    "Marca" character varying(50) NOT NULL,
    "Modelo" character varying(50) NOT NULL,
    "Estado" character varying(20) NOT NULL DEFAULT 'Disponible',
    "FechaProximoMantenimiento" timestamp with time zone
);

CREATE TABLE IF NOT EXISTS public."BloquesDisponibilidad"
(
    "Id" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "IdEquipo" integer NOT NULL REFERENCES public."Equipos"("Id") ON DELETE CASCADE,
    "DiaSemana" character varying(15) NOT NULL,
    "HoraInicio" time without time zone NOT NULL,
    "HoraFin" time without time zone NOT NULL,
    "TipoReserva" character varying(20) NOT NULL
);

CREATE TABLE IF NOT EXISTS public."ReservasEquipo"
(
    "Id" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "IdEquipo" integer NOT NULL REFERENCES public."Equipos"("Id") ON DELETE RESTRICT,
    "IdUsuario" integer NOT NULL REFERENCES public."Usuarios"("Id") ON DELETE RESTRICT,
    "IdBloque" integer REFERENCES public."BloquesDisponibilidad"("Id") ON DELETE SET NULL,
    "FechaReserva" date NOT NULL,
    "HoraInicio" time without time zone NOT NULL,
    "HoraFin" time without time zone NOT NULL,
    "Estado" character varying(20) NOT NULL,
    "ObservacionesCheckOut" text
);

CREATE TABLE IF NOT EXISTS public."Reactivos"
(
    "Id" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "Nombre" character varying(100) NOT NULL,
    "StockActual" numeric NOT NULL,
    "StockMinimo" numeric NOT NULL,
    "UnidadMedida" character varying(20) NOT NULL,
    "Categoria" character varying(50) NOT NULL,
    "FechaCaducidad" timestamp with time zone,
    "ProveedorComprador" character varying(150)
);

CREATE TABLE IF NOT EXISTS public."KardexMovimientos"
(
    "Id" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "IdReactivo" integer NOT NULL REFERENCES public."Reactivos"("Id") ON DELETE RESTRICT,
    "IdUsuario" integer NOT NULL REFERENCES public."Usuarios"("Id") ON DELETE RESTRICT,
    "TipoMovimiento" character varying(20) NOT NULL,
    "Cantidad" numeric NOT NULL,
    "Motivo" character varying(250),
    "FechaMovimiento" timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP
);

COMMIT;
