// <auto-generated />
using System;
using BioUTN.API.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace BioUTN.API.Migrations
{
    [DbContext(typeof(BioUTNContext))]
    [Migration("20260721185923_AddPrioridadesMateriales")]
    partial class AddPrioridadesMateriales
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("BioUTN.Modelos.BloqueDisponibilidad", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("DiaSemana")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("character varying(15)");

                    b.Property<TimeSpan>("HoraFin")
                        .HasColumnType("interval");

                    b.Property<TimeSpan>("HoraInicio")
                        .HasColumnType("interval");

                    b.Property<int>("IdEquipo")
                        .HasColumnType("integer");

                    b.Property<string>("TipoReserva")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.HasKey("Id");

                    b.HasIndex("IdEquipo");

                    b.ToTable("BloquesDisponibilidad");
                });

            modelBuilder.Entity("BioUTN.Modelos.CategoriaDocumento", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Descripcion")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.ToTable("CategoriasDocumento");
                });

            modelBuilder.Entity("BioUTN.Modelos.Documento", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CategoriaId")
                        .HasColumnType("integer");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("FechaSubida")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("IdLoteCultivo")
                        .HasColumnType("integer");

                    b.Property<int?>("IdProyecto")
                        .HasColumnType("integer");

                    b.Property<int>("IdUsuario")
                        .HasColumnType("integer");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<string>("UrlArchivo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("CategoriaId");

                    b.HasIndex("IdLoteCultivo");

                    b.HasIndex("IdProyecto");

                    b.HasIndex("IdUsuario");

                    b.ToTable("Documentos");
                });

            modelBuilder.Entity("BioUTN.Modelos.EntradaDiario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Contenido")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("FechaRegistro")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("IdLoteCultivo")
                        .HasColumnType("integer");

                    b.Property<int>("IdProyecto")
                        .HasColumnType("integer");

                    b.Property<int>("IdUsuario")
                        .HasColumnType("integer");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.HasKey("Id");

                    b.HasIndex("IdLoteCultivo");

                    b.HasIndex("IdProyecto");

                    b.HasIndex("IdUsuario");

                    b.ToTable("EntradasDiario");
                });

            modelBuilder.Entity("BioUTN.Modelos.Equipo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("CodigoInventario")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<DateTime?>("FechaProximoMantenimiento")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Marca")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Modelo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.ToTable("Equipos");
                });

            modelBuilder.Entity("BioUTN.Modelos.Especie", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activo")
                        .HasColumnType("boolean");

                    b.Property<string>("CategoriaUso")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("CicloVida")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("CodigoEstricto")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<short>("DiasResiembra")
                        .HasColumnType("smallint");

                    b.Property<string>("DistribucionNatural")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<bool>("EsEndemica")
                        .HasColumnType("boolean");

                    b.Property<bool>("EsNativa")
                        .HasColumnType("boolean");

                    b.Property<string>("EstadoConservacion")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<int>("IdTaxonomia")
                        .HasColumnType("integer");

                    b.Property<int>("IdTipoPlanta")
                        .HasColumnType("integer");

                    b.Property<string>("ImportanciaEspecie")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<short>("MaxResiembras")
                        .HasColumnType("smallint");

                    b.Property<string>("NombreCientifico")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("NombreComun")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("SinonimosTaxonomicos")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.HasKey("Id");

                    b.HasIndex("IdTaxonomia");

                    b.HasIndex("IdTipoPlanta");

                    b.ToTable("Especies");
                });

            modelBuilder.Entity("BioUTN.Modelos.FaseCultivo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("NombreFase")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.ToTable("FasesCultivo");
                });

            modelBuilder.Entity("BioUTN.Modelos.Genero", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("NombreGenero")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.ToTable("Generos");
                });

            modelBuilder.Entity("BioUTN.Modelos.KardexMovimiento", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Cantidad")
                        .HasColumnType("numeric");

                    b.Property<DateTime>("FechaMovimiento")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("IdReactivo")
                        .HasColumnType("integer");

                    b.Property<int>("IdUsuario")
                        .HasColumnType("integer");

                    b.Property<string>("Motivo")
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)");

                    b.Property<string>("TipoMovimiento")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.HasKey("Id");

                    b.HasIndex("IdReactivo");

                    b.HasIndex("IdUsuario");

                    b.ToTable("KardexMovimientos");
                });

            modelBuilder.Entity("BioUTN.Modelos.LoteCultivo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activo")
                        .HasColumnType("boolean");

                    b.Property<string>("ChecklistSiembra")
                        .HasColumnType("text");

                    b.Property<string>("CodigoTrazabilidad")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<int>("ExplantesPorUnidad")
                        .HasColumnType("integer");

                    b.Property<DateTime>("FechaSiembra")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("IdDocumentoProtocolo")
                        .HasColumnType("integer");

                    b.Property<int>("IdFaseCultivo")
                        .HasColumnType("integer");

                    b.Property<int?>("IdLotePadre")
                        .HasColumnType("integer");

                    b.Property<int>("IdMedioCultivo")
                        .HasColumnType("integer");

                    b.Property<int>("IdPlantaMadre")
                        .HasColumnType("integer");

                    b.Property<int>("IdProyecto")
                        .HasColumnType("integer");

                    b.Property<int>("IdUbicacionFisica")
                        .HasColumnType("integer");

                    b.Property<int?>("IdUnidadFrascoOrigen")
                        .HasColumnType("integer");

                    b.Property<int>("IdUsuario")
                        .HasColumnType("integer");

                    b.Property<int>("NumeroRepique")
                        .HasColumnType("integer");

                    b.Property<string>("TipoExplante")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("TotalExplantesIntroducidos")
                        .HasColumnType("integer");

                    b.Property<int>("TotalUnidades")
                        .HasColumnType("integer");

                    b.Property<string>("UrlQr")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("IdDocumentoProtocolo");

                    b.HasIndex("IdFaseCultivo");

                    b.HasIndex("IdLotePadre");

                    b.HasIndex("IdMedioCultivo");

                    b.HasIndex("IdPlantaMadre");

                    b.HasIndex("IdProyecto");

                    b.HasIndex("IdUbicacionFisica");

                    b.HasIndex("IdUnidadFrascoOrigen");

                    b.HasIndex("IdUsuario");

                    b.ToTable("LotesCultivo");
                });

            modelBuilder.Entity("BioUTN.Modelos.MedioCultivo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Componentes")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<int?>("IdUsuarioPropietario")
                        .HasColumnType("integer");

                    b.Property<string>("Siglas")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("character varying(15)");

                    b.HasKey("Id");

                    b.HasIndex("IdUsuarioPropietario");

                    b.ToTable("MediosCultivo");
                });

            modelBuilder.Entity("BioUTN.Modelos.MonitoreoFitosanitario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Bacterias")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("FechaEvaluacion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("Hongos")
                        .HasColumnType("boolean");

                    b.Property<int>("IdUnidadFrasco")
                        .HasColumnType("integer");

                    b.Property<int>("IdUsuario")
                        .HasColumnType("integer");

                    b.Property<bool>("Muerte")
                        .HasColumnType("boolean");

                    b.Property<string>("NivelContaminacion")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("NivelFenolizacion")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("Observaciones")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("RequiereResiembra")
                        .HasColumnType("boolean");

                    b.Property<string>("Respuesta")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("UnidadesRevisadas")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("IdUnidadFrasco");

                    b.HasIndex("IdUsuario");

                    b.ToTable("MonitoreosFitosanitarios");
                });

            modelBuilder.Entity("BioUTN.Modelos.PermisoAmbiental", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("FechaEmision")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("IdPlantaMadre")
                        .HasColumnType("integer");

                    b.Property<string>("NumeroResolucion")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("UrlArchivoPdf")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("IdPlantaMadre");

                    b.ToTable("PermisosAmbientales");
                });

            modelBuilder.Entity("BioUTN.Modelos.PlantaMadre", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activo")
                        .HasColumnType("boolean");

                    b.Property<string>("CodigoAsignado")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("EstadoFitosanitario")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime?>("FechaColecta")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("FechaRecepcion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("HerbarioReferencia")
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<int?>("IdDocumentoPermiso")
                        .HasColumnType("integer");

                    b.Property<int>("IdEspecie")
                        .HasColumnType("integer");

                    b.Property<int?>("IdProtocolo")
                        .HasColumnType("integer");

                    b.Property<int>("IdProyecto")
                        .HasColumnType("integer");

                    b.Property<int?>("IdResponsableColecta")
                        .HasColumnType("integer");

                    b.Property<int?>("IdResponsableIntroduccion")
                        .HasColumnType("integer");

                    b.Property<int>("IdUsuario")
                        .HasColumnType("integer");

                    b.Property<string>("Observaciones")
                        .HasColumnType("text");

                    b.Property<string>("Procedencia")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("ResponsablesColectaNombres")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("UrlFotografia")
                        .HasColumnType("text");

                    b.Property<string>("UrlQr")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("IdDocumentoPermiso");

                    b.HasIndex("IdEspecie");

                    b.HasIndex("IdProtocolo");

                    b.HasIndex("IdProyecto");

                    b.HasIndex("IdResponsableColecta");

                    b.HasIndex("IdResponsableIntroduccion");

                    b.HasIndex("IdUsuario");

                    b.ToTable("PlantasMadre");
                });

            modelBuilder.Entity("BioUTN.Modelos.Protocolo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activo")
                        .HasColumnType("boolean");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FaseProtocolo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("IdEspecie")
                        .HasColumnType("integer");

                    b.Property<int>("IdUsuarioAutor")
                        .HasColumnType("integer");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<string>("UrlArchivoPdf")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("IdEspecie");

                    b.HasIndex("IdUsuarioAutor");

                    b.ToTable("Protocolos");
                });

            modelBuilder.Entity("BioUTN.Modelos.Proyecto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("DirectoresNombres")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("EstudiantesNombres")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTime?>("FechaFin")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("FechaInicio")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("IdDirector")
                        .HasColumnType("integer");

                    b.Property<int?>("IdEspecie")
                        .HasColumnType("integer");

                    b.Property<int?>("IdTesista")
                        .HasColumnType("integer");

                    b.Property<int>("IdUsuarioResponsable")
                        .HasColumnType("integer");

                    b.Property<string>("NombreProyecto")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<string>("TipoProyecto")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Uso")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.HasIndex("IdDirector");

                    b.HasIndex("IdEspecie");

                    b.HasIndex("IdTesista");

                    b.HasIndex("IdUsuarioResponsable");

                    b.ToTable("Proyectos");
                });

            modelBuilder.Entity("BioUTN.Modelos.Reactivo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Categoria")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime?>("FechaCaducidad")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("IdUnidadMedida")
                        .HasColumnType("integer");

                    b.Property<string>("Marca")
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("ProveedorContacto")
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<string>("ProveedorEmail")
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<string>("ProveedorNombre")
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<string>("ProveedorRUC")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("ProveedorSucursal")
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<string>("ProveedorTelefono")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<decimal>("StockActual")
                        .HasColumnType("numeric");

                    b.Property<decimal>("StockMinimo")
                        .HasColumnType("numeric");

                    b.HasKey("Id");

                    b.HasIndex("IdUnidadMedida");

                    b.ToTable("Reactivos");
                });

            modelBuilder.Entity("BioUTN.Modelos.ReservaEquipo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<DateTime>("FechaReserva")
                        .HasColumnType("timestamp with time zone");

                    b.Property<TimeSpan>("HoraFin")
                        .HasColumnType("interval");

                    b.Property<TimeSpan>("HoraInicio")
                        .HasColumnType("interval");

                    b.Property<int?>("IdBloque")
                        .HasColumnType("integer");

                    b.Property<int>("IdEquipo")
                        .HasColumnType("integer");

                    b.Property<int?>("IdSolicitud")
                        .HasColumnType("integer");

                    b.Property<int>("IdUsuario")
                        .HasColumnType("integer");

                    b.Property<string>("ObservacionesCheckOut")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("IdBloque");

                    b.HasIndex("IdEquipo");

                    b.HasIndex("IdSolicitud");

                    b.HasIndex("IdUsuario");

                    b.ToTable("ReservasEquipo");
                });

            modelBuilder.Entity("BioUTN.Modelos.Rol", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("NombreRol")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.ToTable("Roles");
                });

            modelBuilder.Entity("BioUTN.Modelos.SolicitudDetalleMaterial", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<decimal>("CantidadSolicitada")
                        .HasColumnType("numeric");

                    b.Property<int>("IdReactivo")
                        .HasColumnType("integer");

                    b.Property<int>("IdSolicitud")
                        .HasColumnType("integer");

                    b.Property<string>("Observacion")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("Id");

                    b.HasIndex("IdReactivo");

                    b.HasIndex("IdSolicitud");

                    b.ToTable("SolicitudesDetalleMaterial");
                });

            modelBuilder.Entity("BioUTN.Modelos.SolicitudLab", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<DateTime?>("FechaGestion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("FechaImplementos")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("FechaReactivos")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("FechaReservaEquipo")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("FechaSolicitud")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("HoraFinEquipo")
                        .HasMaxLength(5)
                        .HasColumnType("character varying(5)");

                    b.Property<string>("HoraImplementos")
                        .HasMaxLength(5)
                        .HasColumnType("character varying(5)");

                    b.Property<string>("HoraInicioEquipo")
                        .HasMaxLength(5)
                        .HasColumnType("character varying(5)");

                    b.Property<string>("HoraReactivos")
                        .HasMaxLength(5)
                        .HasColumnType("character varying(5)");

                    b.Property<int?>("IdAprobador")
                        .HasColumnType("integer");

                    b.Property<int?>("IdEquipo")
                        .HasColumnType("integer");

                    b.Property<int>("IdProyecto")
                        .HasColumnType("integer");

                    b.Property<int>("IdSolicitante")
                        .HasColumnType("integer");

                    b.Property<string>("MotivoRechazo")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("Observaciones")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("Prioridad")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("PrioridadImplementos")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("PrioridadReactivos")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("TipoSolicitud")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.HasKey("Id");

                    b.HasIndex("IdAprobador");

                    b.HasIndex("IdEquipo");

                    b.HasIndex("IdProyecto");

                    b.HasIndex("IdSolicitante");

                    b.ToTable("SolicitudesLab");
                });

            modelBuilder.Entity("BioUTN.Modelos.TareaOperativa", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<DateTime>("FechaAsignacion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("FechaCompletada")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("IdUsuario")
                        .HasColumnType("integer");

                    b.Property<string>("TipoTarea")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.HasIndex("IdUsuario");

                    b.ToTable("TareasOperativas");
                });

            modelBuilder.Entity("BioUTN.Modelos.Taxonomia", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Clase")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Dominio")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Especie")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Familia")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("FiloDivision")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Genero")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Orden")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Reino")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("SubFamilia")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("SubReino")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("SubTribu")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Tribu")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.ToTable("Taxonomia");
                });

            modelBuilder.Entity("BioUTN.Modelos.TipoIdentificacion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("NombreTipo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.ToTable("TiposIdentificacion");
                });

            modelBuilder.Entity("BioUTN.Modelos.TipoPlanta", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.ToTable("TiposPlanta");
                });

            modelBuilder.Entity("BioUTN.Modelos.UbicacionFisica", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("CodigoAnaquel")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("EstadoUbicacion")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<int>("LimiteFrascos")
                        .HasColumnType("integer");

                    b.Property<string>("NombreCuerpo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<int>("NumeroPiso")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("UbicacionesFisicas");
                });

            modelBuilder.Entity("BioUTN.Modelos.UnidadFrasco", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activo")
                        .HasColumnType("boolean");

                    b.Property<string>("CodigoUnidad")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<int>("IdLoteCultivo")
                        .HasColumnType("integer");

                    b.Property<int>("NumeroResiembra")
                        .HasColumnType("integer");

                    b.Property<string>("UrlQr")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("IdLoteCultivo");

                    b.ToTable("UnidadesFrasco");
                });

            modelBuilder.Entity("BioUTN.Modelos.UnidadMedida", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Abreviatura")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<decimal>("FactorConversion")
                        .HasColumnType("numeric");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("UnidadBase")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.ToTable("UnidadesMedida");
                });

            modelBuilder.Entity("BioUTN.Modelos.Usuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activo")
                        .HasColumnType("boolean");

                    b.Property<string>("Apellidos")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("ContrasenaHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("CuentaBloqueada")
                        .HasColumnType("boolean");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("IdGenero")
                        .HasColumnType("integer");

                    b.Property<int>("IdRol")
                        .HasColumnType("integer");

                    b.Property<int>("IdTipoIdentificacion")
                        .HasColumnType("integer");

                    b.Property<int>("IntentosFallidos")
                        .HasColumnType("integer");

                    b.Property<string>("Nombres")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("NumeroIdentificacion")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("Telefono")
                        .HasMaxLength(15)
                        .HasColumnType("character varying(15)");

                    b.HasKey("Id");

                    b.HasIndex("IdGenero");

                    b.HasIndex("IdRol");

                    b.HasIndex("IdTipoIdentificacion");

                    b.ToTable("Usuarios");
                });

            modelBuilder.Entity("BioUTN.Modelos.BloqueDisponibilidad", b =>
                {
                    b.HasOne("BioUTN.Modelos.Equipo", "Equipo")
                        .WithMany("Bloques")
                        .HasForeignKey("IdEquipo")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Equipo");
                });

            modelBuilder.Entity("BioUTN.Modelos.Documento", b =>
                {
                    b.HasOne("BioUTN.Modelos.CategoriaDocumento", "Categoria")
                        .WithMany("Documentos")
                        .HasForeignKey("CategoriaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("BioUTN.Modelos.LoteCultivo", "LoteCultivo")
                        .WithMany()
                        .HasForeignKey("IdLoteCultivo");

                    b.HasOne("BioUTN.Modelos.Proyecto", "Proyecto")
                        .WithMany()
                        .HasForeignKey("IdProyecto");

                    b.HasOne("BioUTN.Modelos.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("IdUsuario")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Categoria");

                    b.Navigation("LoteCultivo");

                    b.Navigation("Proyecto");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("BioUTN.Modelos.EntradaDiario", b =>
                {
                    b.HasOne("BioUTN.Modelos.LoteCultivo", "LoteCultivo")
                        .WithMany("EntradasDiario")
                        .HasForeignKey("IdLoteCultivo");

                    b.HasOne("BioUTN.Modelos.Proyecto", "Proyecto")
                        .WithMany("EntradasDiario")
                        .HasForeignKey("IdProyecto")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("BioUTN.Modelos.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("IdUsuario")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("LoteCultivo");

                    b.Navigation("Proyecto");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("BioUTN.Modelos.Especie", b =>
                {
                    b.HasOne("BioUTN.Modelos.Taxonomia", "Taxonomia")
                        .WithMany("Especies")
                        .HasForeignKey("IdTaxonomia")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("BioUTN.Modelos.TipoPlanta", "TipoPlanta")
                        .WithMany()
                        .HasForeignKey("IdTipoPlanta")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Taxonomia");

                    b.Navigation("TipoPlanta");
                });

            modelBuilder.Entity("BioUTN.Modelos.KardexMovimiento", b =>
                {
                    b.HasOne("BioUTN.Modelos.Reactivo", "Reactivo")
                        .WithMany()
                        .HasForeignKey("IdReactivo")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("BioUTN.Modelos.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("IdUsuario")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Reactivo");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("BioUTN.Modelos.LoteCultivo", b =>
                {
                    b.HasOne("BioUTN.Modelos.Documento", "DocumentoProtocolo")
                        .WithMany()
                        .HasForeignKey("IdDocumentoProtocolo");

                    b.HasOne("BioUTN.Modelos.FaseCultivo", "FaseCultivo")
                        .WithMany()
                        .HasForeignKey("IdFaseCultivo")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("BioUTN.Modelos.LoteCultivo", "LotePadre")
                        .WithMany("LotesHijos")
                        .HasForeignKey("IdLotePadre");

                    b.HasOne("BioUTN.Modelos.MedioCultivo", "MedioCultivo")
                        .WithMany()
                        .HasForeignKey("IdMedioCultivo")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("BioUTN.Modelos.PlantaMadre", "PlantaMadre")
                        .WithMany("LotesCultivo")
                        .HasForeignKey("IdPlantaMadre")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("BioUTN.Modelos.Proyecto", "Proyecto")
                        .WithMany("LotesCultivos")
                        .HasForeignKey("IdProyecto")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("BioUTN.Modelos.UbicacionFisica", "UbicacionFisica")
                        .WithMany()
                        .HasForeignKey("IdUbicacionFisica")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("BioUTN.Modelos.UnidadFrasco", "UnidadFrascoOrigen")
                        .WithMany()
                        .HasForeignKey("IdUnidadFrascoOrigen");

                    b.HasOne("BioUTN.Modelos.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("IdUsuario")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("DocumentoProtocolo");

                    b.Navigation("FaseCultivo");

                    b.Navigation("LotePadre");

                    b.Navigation("MedioCultivo");

                    b.Navigation("PlantaMadre");

                    b.Navigation("Proyecto");

                    b.Navigation("UbicacionFisica");

                    b.Navigation("UnidadFrascoOrigen");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("BioUTN.Modelos.MedioCultivo", b =>
                {
                    b.HasOne("BioUTN.Modelos.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("IdUsuarioPropietario");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("BioUTN.Modelos.MonitoreoFitosanitario", b =>
                {
                    b.HasOne("BioUTN.Modelos.UnidadFrasco", "UnidadFrasco")
                        .WithMany("Monitoreos")
                        .HasForeignKey("IdUnidadFrasco")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("BioUTN.Modelos.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("IdUsuario")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("UnidadFrasco");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("BioUTN.Modelos.PermisoAmbiental", b =>
                {
                    b.HasOne("BioUTN.Modelos.PlantaMadre", "PlantaMadre")
                        .WithMany("PermisosAmbientales")
                        .HasForeignKey("IdPlantaMadre")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("PlantaMadre");
                });

            modelBuilder.Entity("BioUTN.Modelos.PlantaMadre", b =>
                {
                    b.HasOne("BioUTN.Modelos.Documento", "DocumentoPermiso")
                        .WithMany()
                        .HasForeignKey("IdDocumentoPermiso");

                    b.HasOne("BioUTN.Modelos.Especie", "Especie")
                        .WithMany("PlantasMadre")
                        .HasForeignKey("IdEspecie")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("BioUTN.Modelos.Protocolo", "Protocolo")
                        .WithMany()
                        .HasForeignKey("IdProtocolo");

                    b.HasOne("BioUTN.Modelos.Proyecto", "Proyecto")
                        .WithMany("PlantasMadres")
                        .HasForeignKey("IdProyecto")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("BioUTN.Modelos.Usuario", "ResponsableColecta")
                        .WithMany()
                        .HasForeignKey("IdResponsableColecta");

                    b.HasOne("BioUTN.Modelos.Usuario", "ResponsableIntroduccion")
                        .WithMany()
                        .HasForeignKey("IdResponsableIntroduccion");

                    b.HasOne("BioUTN.Modelos.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("IdUsuario")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("DocumentoPermiso");

                    b.Navigation("Especie");

                    b.Navigation("Protocolo");

                    b.Navigation("Proyecto");

                    b.Navigation("ResponsableColecta");

                    b.Navigation("ResponsableIntroduccion");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("BioUTN.Modelos.Protocolo", b =>
                {
                    b.HasOne("BioUTN.Modelos.Especie", "Especie")
                        .WithMany("Protocolos")
                        .HasForeignKey("IdEspecie");

                    b.HasOne("BioUTN.Modelos.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("IdUsuarioAutor")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Especie");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("BioUTN.Modelos.Proyecto", b =>
                {
                    b.HasOne("BioUTN.Modelos.Usuario", "Director")
                        .WithMany()
                        .HasForeignKey("IdDirector");

                    b.HasOne("BioUTN.Modelos.Especie", "Especie")
                        .WithMany()
                        .HasForeignKey("IdEspecie");

                    b.HasOne("BioUTN.Modelos.Usuario", "Tesista")
                        .WithMany()
                        .HasForeignKey("IdTesista");

                    b.HasOne("BioUTN.Modelos.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("IdUsuarioResponsable")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Director");

                    b.Navigation("Especie");

                    b.Navigation("Tesista");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("BioUTN.Modelos.Reactivo", b =>
                {
                    b.HasOne("BioUTN.Modelos.UnidadMedida", "UnidadMedidaObj")
                        .WithMany()
                        .HasForeignKey("IdUnidadMedida")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("UnidadMedidaObj");
                });

            modelBuilder.Entity("BioUTN.Modelos.ReservaEquipo", b =>
                {
                    b.HasOne("BioUTN.Modelos.BloqueDisponibilidad", "BloqueDisponibilidad")
                        .WithMany()
                        .HasForeignKey("IdBloque");

                    b.HasOne("BioUTN.Modelos.Equipo", "Equipo")
                        .WithMany("Reservas")
                        .HasForeignKey("IdEquipo")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("BioUTN.Modelos.SolicitudLab", "SolicitudLab")
                        .WithMany()
                        .HasForeignKey("IdSolicitud");

                    b.HasOne("BioUTN.Modelos.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("IdUsuario")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("BloqueDisponibilidad");

                    b.Navigation("Equipo");

                    b.Navigation("SolicitudLab");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("BioUTN.Modelos.SolicitudDetalleMaterial", b =>
                {
                    b.HasOne("BioUTN.Modelos.Reactivo", "Reactivo")
                        .WithMany()
                        .HasForeignKey("IdReactivo")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("BioUTN.Modelos.SolicitudLab", "Solicitud")
                        .WithMany("Detalles")
                        .HasForeignKey("IdSolicitud")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Reactivo");

                    b.Navigation("Solicitud");
                });

            modelBuilder.Entity("BioUTN.Modelos.SolicitudLab", b =>
                {
                    b.HasOne("BioUTN.Modelos.Usuario", "Aprobador")
                        .WithMany()
                        .HasForeignKey("IdAprobador");

                    b.HasOne("BioUTN.Modelos.Equipo", "Equipo")
                        .WithMany()
                        .HasForeignKey("IdEquipo");

                    b.HasOne("BioUTN.Modelos.Proyecto", "Proyecto")
                        .WithMany()
                        .HasForeignKey("IdProyecto")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("BioUTN.Modelos.Usuario", "Solicitante")
                        .WithMany()
                        .HasForeignKey("IdSolicitante")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Aprobador");

                    b.Navigation("Equipo");

                    b.Navigation("Proyecto");

                    b.Navigation("Solicitante");
                });

            modelBuilder.Entity("BioUTN.Modelos.TareaOperativa", b =>
                {
                    b.HasOne("BioUTN.Modelos.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("IdUsuario")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("BioUTN.Modelos.UnidadFrasco", b =>
                {
                    b.HasOne("BioUTN.Modelos.LoteCultivo", "LoteCultivo")
                        .WithMany("UnidadesFrasco")
                        .HasForeignKey("IdLoteCultivo")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("LoteCultivo");
                });

            modelBuilder.Entity("BioUTN.Modelos.Usuario", b =>
                {
                    b.HasOne("BioUTN.Modelos.Genero", "Genero")
                        .WithMany()
                        .HasForeignKey("IdGenero")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("BioUTN.Modelos.Rol", "Rol")
                        .WithMany()
                        .HasForeignKey("IdRol")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("BioUTN.Modelos.TipoIdentificacion", "TipoIdentificacion")
                        .WithMany()
                        .HasForeignKey("IdTipoIdentificacion")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Genero");

                    b.Navigation("Rol");

                    b.Navigation("TipoIdentificacion");
                });

            modelBuilder.Entity("BioUTN.Modelos.CategoriaDocumento", b =>
                {
                    b.Navigation("Documentos");
                });

            modelBuilder.Entity("BioUTN.Modelos.Equipo", b =>
                {
                    b.Navigation("Bloques");

                    b.Navigation("Reservas");
                });

            modelBuilder.Entity("BioUTN.Modelos.Especie", b =>
                {
                    b.Navigation("PlantasMadre");

                    b.Navigation("Protocolos");
                });

            modelBuilder.Entity("BioUTN.Modelos.LoteCultivo", b =>
                {
                    b.Navigation("EntradasDiario");

                    b.Navigation("LotesHijos");

                    b.Navigation("UnidadesFrasco");
                });

            modelBuilder.Entity("BioUTN.Modelos.PlantaMadre", b =>
                {
                    b.Navigation("LotesCultivo");

                    b.Navigation("PermisosAmbientales");
                });

            modelBuilder.Entity("BioUTN.Modelos.Proyecto", b =>
                {
                    b.Navigation("EntradasDiario");

                    b.Navigation("LotesCultivos");

                    b.Navigation("PlantasMadres");
                });

            modelBuilder.Entity("BioUTN.Modelos.SolicitudLab", b =>
                {
                    b.Navigation("Detalles");
                });

            modelBuilder.Entity("BioUTN.Modelos.Taxonomia", b =>
                {
                    b.Navigation("Especies");
                });

            modelBuilder.Entity("BioUTN.Modelos.UnidadFrasco", b =>
                {
                    b.Navigation("Monitoreos");
                });
#pragma warning restore 612, 618
        }
    }
}
