// <auto-generated />
using System;
using BioUTN.API.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace BioUTN.API.Migrations
{
    [DbContext(typeof(BioUTNContext))]
    [Migration("20260719093356_V3_Schema")]
    partial class V3_Schema
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("BioUTN.Modelos.BloqueDisponibilidad", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("DiaSemana")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("character varying(15)");

                    b.Property<TimeSpan>("HoraFin")
                        .HasColumnType("interval");

                    b.Property<TimeSpan>("HoraInicio")
                        .HasColumnType("interval");

                    b.Property<int>("IdEquipo")
                        .HasColumnType("integer");

                    b.Property<string>("TipoReserva")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.HasKey("Id");

                    b.HasIndex("IdEquipo");

                    b.ToTable("BloquesDisponibilidad");
                });

            modelBuilder.Entity("BioUTN.Modelos.EntradaDiario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Contenido")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("FechaRegistro")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("IdLoteCultivo")
                        .HasColumnType("integer");

                    b.Property<int>("IdProyecto")
                        .HasColumnType("integer");

                    b.Property<int>("IdUsuario")
                        .HasColumnType("integer");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.HasKey("Id");

                    b.HasIndex("IdLoteCultivo");

                    b.HasIndex("IdProyecto");

                    b.HasIndex("IdUsuario");

                    b.ToTable("EntradasDiario");
                });

            modelBuilder.Entity("BioUTN.Modelos.Equipo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("CodigoInventario")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<DateTime?>("FechaProximoMantenimiento")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Marca")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Modelo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.ToTable("Equipos");
                });

            modelBuilder.Entity("BioUTN.Modelos.Especie", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activo")
                        .HasColumnType("boolean");

                    b.Property<string>("CodigoEstricto")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<short>("DiasResiembra")
                        .HasColumnType("smallint");

                    b.Property<int>("IdTaxonomia")
                        .HasColumnType("integer");

                    b.Property<int>("IdTipoPlanta")
                        .HasColumnType("integer");

                    b.Property<short>("MaxResiembras")
                        .HasColumnType("smallint");

                    b.Property<string>("NombreCientifico")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("NombreComun")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<bool>("PeligroExtincion")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.HasIndex("IdTaxonomia");

                    b.HasIndex("IdTipoPlanta");

                    b.ToTable("Especies");
                });

            modelBuilder.Entity("BioUTN.Modelos.FaseCultivo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("NombreFase")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.ToTable("FasesCultivo");
                });

            modelBuilder.Entity("BioUTN.Modelos.Genero", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("NombreGenero")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.ToTable("Generos");
                });

            modelBuilder.Entity("BioUTN.Modelos.KardexMovimiento", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Cantidad")
                        .HasColumnType("numeric");

                    b.Property<DateTime>("FechaMovimiento")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("IdReactivo")
                        .HasColumnType("integer");

                    b.Property<int>("IdUsuario")
                        .HasColumnType("integer");

                    b.Property<string>("Motivo")
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)");

                    b.Property<string>("TipoMovimiento")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.HasKey("Id");

                    b.HasIndex("IdReactivo");

                    b.HasIndex("IdUsuario");

                    b.ToTable("KardexMovimientos");
                });

            modelBuilder.Entity("BioUTN.Modelos.LoteCultivo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activo")
                        .HasColumnType("boolean");

                    b.Property<string>("ChecklistSiembra")
                        .HasColumnType("text");

                    b.Property<string>("CodigoTrazabilidad")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime>("FechaSiembra")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("IdFaseCultivo")
                        .HasColumnType("integer");

                    b.Property<int?>("IdLotePadre")
                        .HasColumnType("integer");

                    b.Property<int>("IdMedioCultivo")
                        .HasColumnType("integer");

                    b.Property<int>("IdPlantaMadre")
                        .HasColumnType("integer");

                    b.Property<int>("IdProyecto")
                        .HasColumnType("integer");

                    b.Property<int>("IdUbicacionFisica")
                        .HasColumnType("integer");

                    b.Property<int>("IdUsuario")
                        .HasColumnType("integer");

                    b.Property<int>("NumeroRepique")
                        .HasColumnType("integer");

                    b.Property<int>("TotalUnidades")
                        .HasColumnType("integer");

                    b.Property<string>("UrlQr")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("IdFaseCultivo");

                    b.HasIndex("IdLotePadre");

                    b.HasIndex("IdMedioCultivo");

                    b.HasIndex("IdPlantaMadre");

                    b.HasIndex("IdProyecto");

                    b.HasIndex("IdUbicacionFisica");

                    b.HasIndex("IdUsuario");

                    b.ToTable("LotesCultivo");
                });

            modelBuilder.Entity("BioUTN.Modelos.MedioCultivo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Componentes")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<int?>("IdUsuarioPropietario")
                        .HasColumnType("integer");

                    b.Property<string>("Siglas")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("character varying(15)");

                    b.HasKey("Id");

                    b.HasIndex("IdUsuarioPropietario");

                    b.ToTable("MediosCultivo");
                });

            modelBuilder.Entity("BioUTN.Modelos.MonitoreoFitosanitario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Bacterias")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("FechaEvaluacion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("Hongos")
                        .HasColumnType("boolean");

                    b.Property<int>("IdUnidadFrasco")
                        .HasColumnType("integer");

                    b.Property<int>("IdUsuario")
                        .HasColumnType("integer");

                    b.Property<string>("NivelContaminacion")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("NivelFenolizacion")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("Observaciones")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("IdUnidadFrasco");

                    b.HasIndex("IdUsuario");

                    b.ToTable("MonitoreosFitosanitarios");
                });

            modelBuilder.Entity("BioUTN.Modelos.PermisoAmbiental", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("FechaEmision")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("IdPlantaMadre")
                        .HasColumnType("integer");

                    b.Property<string>("NumeroResolucion")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("UrlArchivoPdf")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("IdPlantaMadre");

                    b.ToTable("PermisosAmbientales");
                });

            modelBuilder.Entity("BioUTN.Modelos.PlantaMadre", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activo")
                        .HasColumnType("boolean");

                    b.Property<string>("CodigoAsignado")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("EstadoFitosanitario")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime>("FechaIntroduccion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("IdEspecie")
                        .HasColumnType("integer");

                    b.Property<int>("IdProyecto")
                        .HasColumnType("integer");

                    b.Property<int>("IdUsuario")
                        .HasColumnType("integer");

                    b.Property<string>("UrlFotografia")
                        .HasColumnType("text");

                    b.Property<string>("UrlQr")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("IdEspecie");

                    b.HasIndex("IdProyecto");

                    b.HasIndex("IdUsuario");

                    b.ToTable("PlantasMadre");
                });

            modelBuilder.Entity("BioUTN.Modelos.Protocolo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activo")
                        .HasColumnType("boolean");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FaseProtocolo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("IdEspecie")
                        .HasColumnType("integer");

                    b.Property<int>("IdUsuarioAutor")
                        .HasColumnType("integer");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<string>("UrlArchivoPdf")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("IdEspecie");

                    b.HasIndex("IdUsuarioAutor");

                    b.ToTable("Protocolos");
                });

            modelBuilder.Entity("BioUTN.Modelos.Proyecto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<DateTime?>("FechaFin")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("FechaInicio")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("IdUsuarioResponsable")
                        .HasColumnType("integer");

                    b.Property<string>("NombreProyecto")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<string>("TipoProyecto")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.HasIndex("IdUsuarioResponsable");

                    b.ToTable("Proyectos");
                });

            modelBuilder.Entity("BioUTN.Modelos.Reactivo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Categoria")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime?>("FechaCaducidad")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("ProveedorComprador")
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<decimal>("StockActual")
                        .HasColumnType("numeric");

                    b.Property<decimal>("StockMinimo")
                        .HasColumnType("numeric");

                    b.Property<string>("UnidadMedida")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.HasKey("Id");

                    b.ToTable("Reactivos");
                });

            modelBuilder.Entity("BioUTN.Modelos.ReservaEquipo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<DateTime>("FechaReserva")
                        .HasColumnType("timestamp with time zone");

                    b.Property<TimeSpan>("HoraFin")
                        .HasColumnType("interval");

                    b.Property<TimeSpan>("HoraInicio")
                        .HasColumnType("interval");

                    b.Property<int?>("IdBloque")
                        .HasColumnType("integer");

                    b.Property<int>("IdEquipo")
                        .HasColumnType("integer");

                    b.Property<int>("IdUsuario")
                        .HasColumnType("integer");

                    b.Property<string>("ObservacionesCheckOut")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("IdBloque");

                    b.HasIndex("IdEquipo");

                    b.HasIndex("IdUsuario");

                    b.ToTable("ReservasEquipo");
                });

            modelBuilder.Entity("BioUTN.Modelos.Rol", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("NombreRol")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.ToTable("Roles");
                });

            modelBuilder.Entity("BioUTN.Modelos.TareaOperativa", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<DateTime>("FechaAsignacion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("FechaCompletada")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("IdUsuario")
                        .HasColumnType("integer");

                    b.Property<string>("TipoTarea")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.HasIndex("IdUsuario");

                    b.ToTable("TareasOperativas");
                });

            modelBuilder.Entity("BioUTN.Modelos.Taxonomia", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Clase")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Dominio")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Especie")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Familia")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("FiloDivision")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Genero")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Orden")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Reino")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("SubFamilia")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("SubReino")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("SubTribu")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Tribu")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.ToTable("Taxonomia");
                });

            modelBuilder.Entity("BioUTN.Modelos.TipoIdentificacion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("NombreTipo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.ToTable("TiposIdentificacion");
                });

            modelBuilder.Entity("BioUTN.Modelos.TipoPlanta", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.ToTable("TiposPlanta");
                });

            modelBuilder.Entity("BioUTN.Modelos.UbicacionFisica", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("CodigoAnaquel")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("EstadoUbicacion")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("NombreCuerpo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<int>("NumeroPiso")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("UbicacionesFisicas");
                });

            modelBuilder.Entity("BioUTN.Modelos.UnidadFrasco", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activo")
                        .HasColumnType("boolean");

                    b.Property<string>("CodigoUnidad")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<int>("IdLoteCultivo")
                        .HasColumnType("integer");

                    b.Property<int>("NumeroResiembra")
                        .HasColumnType("integer");

                    b.Property<string>("UrlQr")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("IdLoteCultivo");

                    b.ToTable("UnidadesFrasco");
                });

            modelBuilder.Entity("BioUTN.Modelos.Usuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activo")
                        .HasColumnType("boolean");

                    b.Property<string>("Apellidos")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("ContrasenaHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("CuentaBloqueada")
                        .HasColumnType("boolean");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("IdGenero")
                        .HasColumnType("integer");

                    b.Property<int>("IdRol")
                        .HasColumnType("integer");

                    b.Property<int>("IdTipoIdentificacion")
                        .HasColumnType("integer");

                    b.Property<int>("IntentosFallidos")
                        .HasColumnType("integer");

                    b.Property<string>("Nombres")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("NumeroIdentificacion")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("Telefono")
                        .HasMaxLength(15)
                        .HasColumnType("character varying(15)");

                    b.HasKey("Id");

                    b.HasIndex("IdGenero");

                    b.HasIndex("IdRol");

                    b.HasIndex("IdTipoIdentificacion");

                    b.ToTable("Usuarios");
                });

            modelBuilder.Entity("BioUTN.Modelos.BloqueDisponibilidad", b =>
                {
                    b.HasOne("BioUTN.Modelos.Equipo", "Equipo")
                        .WithMany("Bloques")
                        .HasForeignKey("IdEquipo")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Equipo");
                });

            modelBuilder.Entity("BioUTN.Modelos.EntradaDiario", b =>
                {
                    b.HasOne("BioUTN.Modelos.LoteCultivo", "LoteCultivo")
                        .WithMany("EntradasDiario")
                        .HasForeignKey("IdLoteCultivo");

                    b.HasOne("BioUTN.Modelos.Proyecto", "Proyecto")
                        .WithMany("EntradasDiario")
                        .HasForeignKey("IdProyecto")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("BioUTN.Modelos.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("IdUsuario")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("LoteCultivo");

                    b.Navigation("Proyecto");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("BioUTN.Modelos.Especie", b =>
                {
                    b.HasOne("BioUTN.Modelos.Taxonomia", "Taxonomia")
                        .WithMany("Especies")
                        .HasForeignKey("IdTaxonomia")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("BioUTN.Modelos.TipoPlanta", "TipoPlanta")
                        .WithMany()
                        .HasForeignKey("IdTipoPlanta")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Taxonomia");

                    b.Navigation("TipoPlanta");
                });

            modelBuilder.Entity("BioUTN.Modelos.KardexMovimiento", b =>
                {
                    b.HasOne("BioUTN.Modelos.Reactivo", "Reactivo")
                        .WithMany()
                        .HasForeignKey("IdReactivo")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("BioUTN.Modelos.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("IdUsuario")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Reactivo");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("BioUTN.Modelos.LoteCultivo", b =>
                {
                    b.HasOne("BioUTN.Modelos.FaseCultivo", "FaseCultivo")
                        .WithMany()
                        .HasForeignKey("IdFaseCultivo")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("BioUTN.Modelos.LoteCultivo", "LotePadre")
                        .WithMany("LotesHijos")
                        .HasForeignKey("IdLotePadre");

                    b.HasOne("BioUTN.Modelos.MedioCultivo", "MedioCultivo")
                        .WithMany()
                        .HasForeignKey("IdMedioCultivo")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("BioUTN.Modelos.PlantaMadre", "PlantaMadre")
                        .WithMany("LotesCultivo")
                        .HasForeignKey("IdPlantaMadre")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("BioUTN.Modelos.Proyecto", "Proyecto")
                        .WithMany("LotesCultivos")
                        .HasForeignKey("IdProyecto")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("BioUTN.Modelos.UbicacionFisica", "UbicacionFisica")
                        .WithMany()
                        .HasForeignKey("IdUbicacionFisica")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("BioUTN.Modelos.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("IdUsuario")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("FaseCultivo");

                    b.Navigation("LotePadre");

                    b.Navigation("MedioCultivo");

                    b.Navigation("PlantaMadre");

                    b.Navigation("Proyecto");

                    b.Navigation("UbicacionFisica");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("BioUTN.Modelos.MedioCultivo", b =>
                {
                    b.HasOne("BioUTN.Modelos.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("IdUsuarioPropietario");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("BioUTN.Modelos.MonitoreoFitosanitario", b =>
                {
                    b.HasOne("BioUTN.Modelos.UnidadFrasco", "UnidadFrasco")
                        .WithMany("Monitoreos")
                        .HasForeignKey("IdUnidadFrasco")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("BioUTN.Modelos.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("IdUsuario")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("UnidadFrasco");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("BioUTN.Modelos.PermisoAmbiental", b =>
                {
                    b.HasOne("BioUTN.Modelos.PlantaMadre", "PlantaMadre")
                        .WithMany("PermisosAmbientales")
                        .HasForeignKey("IdPlantaMadre")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("PlantaMadre");
                });

            modelBuilder.Entity("BioUTN.Modelos.PlantaMadre", b =>
                {
                    b.HasOne("BioUTN.Modelos.Especie", "Especie")
                        .WithMany("PlantasMadre")
                        .HasForeignKey("IdEspecie")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("BioUTN.Modelos.Proyecto", "Proyecto")
                        .WithMany("PlantasMadres")
                        .HasForeignKey("IdProyecto")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("BioUTN.Modelos.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("IdUsuario")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Especie");

                    b.Navigation("Proyecto");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("BioUTN.Modelos.Protocolo", b =>
                {
                    b.HasOne("BioUTN.Modelos.Especie", "Especie")
                        .WithMany("Protocolos")
                        .HasForeignKey("IdEspecie");

                    b.HasOne("BioUTN.Modelos.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("IdUsuarioAutor")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Especie");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("BioUTN.Modelos.Proyecto", b =>
                {
                    b.HasOne("BioUTN.Modelos.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("IdUsuarioResponsable")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("BioUTN.Modelos.ReservaEquipo", b =>
                {
                    b.HasOne("BioUTN.Modelos.BloqueDisponibilidad", "BloqueDisponibilidad")
                        .WithMany()
                        .HasForeignKey("IdBloque");

                    b.HasOne("BioUTN.Modelos.Equipo", "Equipo")
                        .WithMany("Reservas")
                        .HasForeignKey("IdEquipo")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("BioUTN.Modelos.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("IdUsuario")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("BloqueDisponibilidad");

                    b.Navigation("Equipo");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("BioUTN.Modelos.TareaOperativa", b =>
                {
                    b.HasOne("BioUTN.Modelos.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("IdUsuario")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("BioUTN.Modelos.UnidadFrasco", b =>
                {
                    b.HasOne("BioUTN.Modelos.LoteCultivo", "LoteCultivo")
                        .WithMany("UnidadesFrasco")
                        .HasForeignKey("IdLoteCultivo")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("LoteCultivo");
                });

            modelBuilder.Entity("BioUTN.Modelos.Usuario", b =>
                {
                    b.HasOne("BioUTN.Modelos.Genero", "Genero")
                        .WithMany()
                        .HasForeignKey("IdGenero")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("BioUTN.Modelos.Rol", "Rol")
                        .WithMany()
                        .HasForeignKey("IdRol")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("BioUTN.Modelos.TipoIdentificacion", "TipoIdentificacion")
                        .WithMany()
                        .HasForeignKey("IdTipoIdentificacion")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Genero");

                    b.Navigation("Rol");

                    b.Navigation("TipoIdentificacion");
                });

            modelBuilder.Entity("BioUTN.Modelos.Equipo", b =>
                {
                    b.Navigation("Bloques");

                    b.Navigation("Reservas");
                });

            modelBuilder.Entity("BioUTN.Modelos.Especie", b =>
                {
                    b.Navigation("PlantasMadre");

                    b.Navigation("Protocolos");
                });

            modelBuilder.Entity("BioUTN.Modelos.LoteCultivo", b =>
                {
                    b.Navigation("EntradasDiario");

                    b.Navigation("LotesHijos");

                    b.Navigation("UnidadesFrasco");
                });

            modelBuilder.Entity("BioUTN.Modelos.PlantaMadre", b =>
                {
                    b.Navigation("LotesCultivo");

                    b.Navigation("PermisosAmbientales");
                });

            modelBuilder.Entity("BioUTN.Modelos.Proyecto", b =>
                {
                    b.Navigation("EntradasDiario");

                    b.Navigation("LotesCultivos");

                    b.Navigation("PlantasMadres");
                });

            modelBuilder.Entity("BioUTN.Modelos.Taxonomia", b =>
                {
                    b.Navigation("Especies");
                });

            modelBuilder.Entity("BioUTN.Modelos.UnidadFrasco", b =>
                {
                    b.Navigation("Monitoreos");
                });
#pragma warning restore 612, 618
        }
    }
}
