// <auto-generated />
using System;
using BioUTN.API.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace BioUTN.API.Migrations
{
    [DbContext(typeof(BioUTNContext))]
    [Migration("20260713050622_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("BioUTN.Modelos.Documento", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Categoria")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("FechaSubida")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("IdLoteCultivo")
                        .HasColumnType("integer");

                    b.Property<int?>("IdProyecto")
                        .HasColumnType("integer");

                    b.Property<int>("IdUsuario")
                        .HasColumnType("integer");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<string>("UrlArchivo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("IdLoteCultivo");

                    b.HasIndex("IdProyecto");

                    b.HasIndex("IdUsuario");

                    b.ToTable("Documentos");
                });

            modelBuilder.Entity("BioUTN.Modelos.Equipo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("CodigoInventario")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<DateTime?>("FechaProximoMantenimiento")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Marca")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Modelo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.ToTable("Equipos");
                });

            modelBuilder.Entity("BioUTN.Modelos.Especie", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("CodigoEstricto")
                        .IsRequired()
                        .HasMaxLength(5)
                        .HasColumnType("character varying(5)");

                    b.Property<int>("IdFamilia")
                        .HasColumnType("integer");

                    b.Property<int>("IdTipoPlanta")
                        .HasColumnType("integer");

                    b.Property<string>("NombreCientifico")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("NombreComun")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<bool>("PeligroExtincion")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.HasIndex("IdFamilia");

                    b.HasIndex("IdTipoPlanta");

                    b.ToTable("Especies");
                });

            modelBuilder.Entity("BioUTN.Modelos.Familia", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("NombreFamilia")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.ToTable("Familias");
                });

            modelBuilder.Entity("BioUTN.Modelos.FaseCultivo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("NombreFase")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.ToTable("FasesCultivo");
                });

            modelBuilder.Entity("BioUTN.Modelos.Genero", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("NombreGenero")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.ToTable("Generos");
                });

            modelBuilder.Entity("BioUTN.Modelos.LoteCultivo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("CodigoTrazabilidad")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime>("FechaSiembra")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("IdFaseCultivo")
                        .HasColumnType("integer");

                    b.Property<int?>("IdLotePadre")
                        .HasColumnType("integer");

                    b.Property<int>("IdMedioCultivo")
                        .HasColumnType("integer");

                    b.Property<int>("IdPlantaMadre")
                        .HasColumnType("integer");

                    b.Property<int>("IdProyecto")
                        .HasColumnType("integer");

                    b.Property<int>("IdTipoCultivo")
                        .HasColumnType("integer");

                    b.Property<int>("IdUbicacionFisica")
                        .HasColumnType("integer");

                    b.Property<int>("NumeroRepique")
                        .HasColumnType("integer");

                    b.Property<int?>("UsuarioId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("IdFaseCultivo");

                    b.HasIndex("IdLotePadre");

                    b.HasIndex("IdMedioCultivo");

                    b.HasIndex("IdPlantaMadre");

                    b.HasIndex("IdProyecto");

                    b.HasIndex("IdTipoCultivo");

                    b.HasIndex("IdUbicacionFisica");

                    b.HasIndex("UsuarioId");

                    b.ToTable("LotesCultivo");
                });

            modelBuilder.Entity("BioUTN.Modelos.MedioCultivo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Siglas")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.HasKey("Id");

                    b.ToTable("MediosCultivo");
                });

            modelBuilder.Entity("BioUTN.Modelos.MonitoreoFitosanitario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("FechaEvaluacion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("IdLoteCultivo")
                        .HasColumnType("integer");

                    b.Property<int>("IdUsuario")
                        .HasColumnType("integer");

                    b.Property<string>("NivelContaminacion")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("NivelFenolizacion")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("Observaciones")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("IdLoteCultivo");

                    b.HasIndex("IdUsuario");

                    b.ToTable("MonitoreosFitosanitarios");
                });

            modelBuilder.Entity("BioUTN.Modelos.PermisoAmbiental", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("FechaEmision")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("IdPlantaMadre")
                        .HasColumnType("integer");

                    b.Property<string>("NumeroResolucion")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("UrlArchivoPdf")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("IdPlantaMadre");

                    b.ToTable("PermisosAmbientales");
                });

            modelBuilder.Entity("BioUTN.Modelos.PlantaMadre", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("CodigoAsignado")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<string>("EstadoFitosanitario")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime>("FechaIntroduccion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("IdEspecie")
                        .HasColumnType("integer");

                    b.Property<int>("IdProyecto")
                        .HasColumnType("integer");

                    b.Property<string>("UrlFotografia")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("UsuarioId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("IdEspecie");

                    b.HasIndex("IdProyecto");

                    b.HasIndex("UsuarioId");

                    b.ToTable("PlantasMadre");
                });

            modelBuilder.Entity("BioUTN.Modelos.Proyecto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<DateTime?>("FechaFin")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("FechaInicio")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("NombreProyecto")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<string>("TipoProyecto")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.ToTable("Proyectos");
                });

            modelBuilder.Entity("BioUTN.Modelos.ProyectoUsuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("IdProyecto")
                        .HasColumnType("integer");

                    b.Property<int>("IdUsuario")
                        .HasColumnType("integer");

                    b.Property<string>("RolEnProyecto")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.HasIndex("IdProyecto");

                    b.HasIndex("IdUsuario");

                    b.ToTable("ProyectosUsuarios");
                });

            modelBuilder.Entity("BioUTN.Modelos.Reactivo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("FechaCaducidad")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("ProveedorComprador")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<decimal>("StockActual")
                        .HasColumnType("numeric");

                    b.Property<decimal>("StockMinimo")
                        .HasColumnType("numeric");

                    b.Property<string>("UnidadMedida")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.HasKey("Id");

                    b.ToTable("Reactivos");
                });

            modelBuilder.Entity("BioUTN.Modelos.ReservaEquipo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<DateTime>("FechaFin")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("FechaInicio")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("IdEquipo")
                        .HasColumnType("integer");

                    b.Property<int>("IdUsuario")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("IdEquipo");

                    b.HasIndex("IdUsuario");

                    b.ToTable("ReservasEquipo");
                });

            modelBuilder.Entity("BioUTN.Modelos.Rol", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("NombreRol")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.ToTable("Roles");
                });

            modelBuilder.Entity("BioUTN.Modelos.TareaOperativa", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<DateTime>("FechaAsignacion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("FechaCompletada")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("IdUsuario")
                        .HasColumnType("integer");

                    b.Property<string>("TipoTarea")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.HasIndex("IdUsuario");

                    b.ToTable("TareasOperativas");
                });

            modelBuilder.Entity("BioUTN.Modelos.TipoCultivo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("NombreTipo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.ToTable("TiposCultivo");
                });

            modelBuilder.Entity("BioUTN.Modelos.TipoIdentificacion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("NombreTipo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.ToTable("TiposIdentificacion");
                });

            modelBuilder.Entity("BioUTN.Modelos.TipoPlanta", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.ToTable("TiposPlanta");
                });

            modelBuilder.Entity("BioUTN.Modelos.UbicacionFisica", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("EstadoUbicacion")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("NombreCuerpo")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<int>("NumeroPiso")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("UbicacionesFisicas");
                });

            modelBuilder.Entity("BioUTN.Modelos.Usuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Apellidos")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ContrasenaHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool?>("CuentaBloqueada")
                        .HasColumnType("boolean");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("IdGenero")
                        .HasColumnType("integer");

                    b.Property<int>("IdRol")
                        .HasColumnType("integer");

                    b.Property<int>("IdTipoIdentificacion")
                        .HasColumnType("integer");

                    b.Property<int>("IntentosFallidos")
                        .HasColumnType("integer");

                    b.Property<string>("Nombres")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("NumeroIdentificacion")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("IdGenero");

                    b.HasIndex("IdRol");

                    b.HasIndex("IdTipoIdentificacion");

                    b.ToTable("Usuarios");
                });

            modelBuilder.Entity("BioUTN.Modelos.Documento", b =>
                {
                    b.HasOne("BioUTN.Modelos.LoteCultivo", "LoteCultivo")
                        .WithMany("DocumentosAdjuntos")
                        .HasForeignKey("IdLoteCultivo");

                    b.HasOne("BioUTN.Modelos.Proyecto", "Proyecto")
                        .WithMany("Documentos")
                        .HasForeignKey("IdProyecto");

                    b.HasOne("BioUTN.Modelos.Usuario", "Usuario")
                        .WithMany("DocumentosSubidos")
                        .HasForeignKey("IdUsuario")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("LoteCultivo");

                    b.Navigation("Proyecto");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("BioUTN.Modelos.Especie", b =>
                {
                    b.HasOne("BioUTN.Modelos.Familia", "Familia")
                        .WithMany("Especies")
                        .HasForeignKey("IdFamilia")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("BioUTN.Modelos.TipoPlanta", "TipoPlanta")
                        .WithMany("Especies")
                        .HasForeignKey("IdTipoPlanta")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Familia");

                    b.Navigation("TipoPlanta");
                });

            modelBuilder.Entity("BioUTN.Modelos.LoteCultivo", b =>
                {
                    b.HasOne("BioUTN.Modelos.FaseCultivo", "FaseCultivo")
                        .WithMany("LotesCultivos")
                        .HasForeignKey("IdFaseCultivo")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("BioUTN.Modelos.LoteCultivo", "LotePadre")
                        .WithMany("LotesHijos")
                        .HasForeignKey("IdLotePadre");

                    b.HasOne("BioUTN.Modelos.MedioCultivo", "MedioCultivo")
                        .WithMany()
                        .HasForeignKey("IdMedioCultivo")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("BioUTN.Modelos.PlantaMadre", "PlantaMadre")
                        .WithMany("LotesCultivo")
                        .HasForeignKey("IdPlantaMadre")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("BioUTN.Modelos.Proyecto", "Proyecto")
                        .WithMany("LotesCultivos")
                        .HasForeignKey("IdProyecto")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("BioUTN.Modelos.TipoCultivo", "TipoCultivo")
                        .WithMany("LotesCultivos")
                        .HasForeignKey("IdTipoCultivo")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("BioUTN.Modelos.UbicacionFisica", "UbicacionFisica")
                        .WithMany("LotesCultivos")
                        .HasForeignKey("IdUbicacionFisica")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("BioUTN.Modelos.Usuario", null)
                        .WithMany("LotesAsignados")
                        .HasForeignKey("UsuarioId");

                    b.Navigation("FaseCultivo");

                    b.Navigation("LotePadre");

                    b.Navigation("MedioCultivo");

                    b.Navigation("PlantaMadre");

                    b.Navigation("Proyecto");

                    b.Navigation("TipoCultivo");

                    b.Navigation("UbicacionFisica");
                });

            modelBuilder.Entity("BioUTN.Modelos.MonitoreoFitosanitario", b =>
                {
                    b.HasOne("BioUTN.Modelos.LoteCultivo", "LoteCultivo")
                        .WithMany("Monitoreos")
                        .HasForeignKey("IdLoteCultivo")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("BioUTN.Modelos.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("IdUsuario")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("LoteCultivo");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("BioUTN.Modelos.PermisoAmbiental", b =>
                {
                    b.HasOne("BioUTN.Modelos.PlantaMadre", "PlantaMadre")
                        .WithMany("PermisosAmbientales")
                        .HasForeignKey("IdPlantaMadre")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("PlantaMadre");
                });

            modelBuilder.Entity("BioUTN.Modelos.PlantaMadre", b =>
                {
                    b.HasOne("BioUTN.Modelos.Especie", "Especie")
                        .WithMany("PlantasMadre")
                        .HasForeignKey("IdEspecie")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("BioUTN.Modelos.Proyecto", "Proyecto")
                        .WithMany("PlantasMadres")
                        .HasForeignKey("IdProyecto")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("BioUTN.Modelos.Usuario", null)
                        .WithMany("PlantasIntroducidas")
                        .HasForeignKey("UsuarioId");

                    b.Navigation("Especie");

                    b.Navigation("Proyecto");
                });

            modelBuilder.Entity("BioUTN.Modelos.ProyectoUsuario", b =>
                {
                    b.HasOne("BioUTN.Modelos.Proyecto", "Proyecto")
                        .WithMany("UsuariosAsignados")
                        .HasForeignKey("IdProyecto")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("BioUTN.Modelos.Usuario", "Usuario")
                        .WithMany("ProyectosAsignados")
                        .HasForeignKey("IdUsuario")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Proyecto");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("BioUTN.Modelos.ReservaEquipo", b =>
                {
                    b.HasOne("BioUTN.Modelos.Equipo", "Equipo")
                        .WithMany("Reservas")
                        .HasForeignKey("IdEquipo")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("BioUTN.Modelos.Usuario", "Usuario")
                        .WithMany("Reservas")
                        .HasForeignKey("IdUsuario")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Equipo");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("BioUTN.Modelos.TareaOperativa", b =>
                {
                    b.HasOne("BioUTN.Modelos.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("IdUsuario")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("BioUTN.Modelos.Usuario", b =>
                {
                    b.HasOne("BioUTN.Modelos.Genero", "Genero")
                        .WithMany("Usuarios")
                        .HasForeignKey("IdGenero")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("BioUTN.Modelos.Rol", "Rol")
                        .WithMany("Usuarios")
                        .HasForeignKey("IdRol")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("BioUTN.Modelos.TipoIdentificacion", "TipoIdentificacion")
                        .WithMany("Usuarios")
                        .HasForeignKey("IdTipoIdentificacion")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Genero");

                    b.Navigation("Rol");

                    b.Navigation("TipoIdentificacion");
                });

            modelBuilder.Entity("BioUTN.Modelos.Equipo", b =>
                {
                    b.Navigation("Reservas");
                });

            modelBuilder.Entity("BioUTN.Modelos.Especie", b =>
                {
                    b.Navigation("PlantasMadre");
                });

            modelBuilder.Entity("BioUTN.Modelos.Familia", b =>
                {
                    b.Navigation("Especies");
                });

            modelBuilder.Entity("BioUTN.Modelos.FaseCultivo", b =>
                {
                    b.Navigation("LotesCultivos");
                });

            modelBuilder.Entity("BioUTN.Modelos.Genero", b =>
                {
                    b.Navigation("Usuarios");
                });

            modelBuilder.Entity("BioUTN.Modelos.LoteCultivo", b =>
                {
                    b.Navigation("DocumentosAdjuntos");

                    b.Navigation("LotesHijos");

                    b.Navigation("Monitoreos");
                });

            modelBuilder.Entity("BioUTN.Modelos.PlantaMadre", b =>
                {
                    b.Navigation("LotesCultivo");

                    b.Navigation("PermisosAmbientales");
                });

            modelBuilder.Entity("BioUTN.Modelos.Proyecto", b =>
                {
                    b.Navigation("Documentos");

                    b.Navigation("LotesCultivos");

                    b.Navigation("PlantasMadres");

                    b.Navigation("UsuariosAsignados");
                });

            modelBuilder.Entity("BioUTN.Modelos.Rol", b =>
                {
                    b.Navigation("Usuarios");
                });

            modelBuilder.Entity("BioUTN.Modelos.TipoCultivo", b =>
                {
                    b.Navigation("LotesCultivos");
                });

            modelBuilder.Entity("BioUTN.Modelos.TipoIdentificacion", b =>
                {
                    b.Navigation("Usuarios");
                });

            modelBuilder.Entity("BioUTN.Modelos.TipoPlanta", b =>
                {
                    b.Navigation("Especies");
                });

            modelBuilder.Entity("BioUTN.Modelos.UbicacionFisica", b =>
                {
                    b.Navigation("LotesCultivos");
                });

            modelBuilder.Entity("BioUTN.Modelos.Usuario", b =>
                {
                    b.Navigation("DocumentosSubidos");

                    b.Navigation("LotesAsignados");

                    b.Navigation("PlantasIntroducidas");

                    b.Navigation("ProyectosAsignados");

                    b.Navigation("Reservas");
                });
#pragma warning restore 612, 618
        }
    }
}
